version: '3.8'

services:
  postgresql:
    build: './'
    container_name: fitnext-db
    environment:
      - POSTGRESQL_USERNAME=bdr
      - POSTGRESQL_PASSWORD=bdr
      - POSTGRESQL_DATABASE=bdr
      - POSTGRESQL_POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
